version: 2.1

workflows:
  test-deploy:
    jobs:
      - test
      - test 2
jobs:
  test:
    docker:
      - image: cimg/node:17.1.0
    steps:
      - checkout
      - run:
          name: install dependencies
          command: npm install
   
  test-2:
    docker:
      - image: cimg/node:17.1.0
    steps:
      - checkout
      - run:
          name: install dependencies
          command: npm install
      
